version: '3.8'

services:
  redis:
    image: personaltutorfastapi.azurecr.io/redis:alpine
    ports:
      - '6379:6379'

  fastapi:
    build: .
    image: personaltutorfastapi.azurecr.io/personal_tutor_backend:build-tag-1
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - redis
