name: Run Tests then Upload Container to Docker Hub and Azure Container Registry

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/personal_tutor_backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/personal_tutor_backend:latest

  azure_acr:
    runs-on: ubuntu-latest
    needs: docker
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/personal_tutor_backend:latest

      - name: Tag Docker image for Azure Container Registry
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/personal_tutor_backend:latest ${{ secrets.ACR_LOGIN_SERVER }}/personal_tutor_backend:latest

      - name: Push Docker image to Azure Container Registry
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/personal_tutor_backend:latest
